library(dplyr)

metadata <- read.csv("metadata_parsed_200.tsv", sep = "\t", check.names = F)

output <- data.frame(ID = metadata[,c(1)])
output$pdbx_details <- metadata$pdbx_details %>% gsub(pattern="\t", replacement="")
output$peg = ifelse(rowSums(metadata[,grep("peg", colnames(metadata))]!=0)>0, 1, 0)
output$hepes = ifelse(rowSums(metadata[,grep("hepes", colnames(metadata))]!=0)>0, 1, 0)
output$sodium = ifelse(rowSums(metadata[,grep("sodium", colnames(metadata))]!=0)>0, 1, 0)
output$ammonium = ifelse(rowSums(metadata[,grep("ammonium", colnames(metadata))]!=0)>0, 1, 0)
output$tris = ifelse(rowSums(metadata[,grep("tris", colnames(metadata))]!=0)>0, 1, 0)
output$acetate = ifelse(rowSums(metadata[,grep("acetate", colnames(metadata))]!=0)>0, 1, 0)
output$phosphate = ifelse(rowSums(metadata[,grep("phosphate", colnames(metadata))]!=0)>0, 1, 0)
output$chloride = ifelse(rowSums(metadata[,grep("chloride", colnames(metadata))]!=0)>0, 1, 0)
output$magnesium = ifelse(rowSums(metadata[,grep("magnesium", colnames(metadata))]!=0)>0, 1, 0)
output$lithium_chloride = ifelse((metadata[,grep("lithium chloride", colnames(metadata))]!=0)>0, 1, 0)
output$sodium_cacodylate = ifelse(rowSums(metadata[,grep("sodium cacodylate", colnames(metadata))]!=0)>0, 1, 0)
output$ammonium_sulfate = ifelse(rowSums(metadata[,grep("ammonium sulfate", colnames(metadata))]!=0)>0, 1, 0)

write.table(output, "metadata_condensed_9.tsv", sep = "\t", row.names = F)
